### PR TITLE
Update to CBC 2.10.5

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR provides an updated version of the CBC optimization software library and header files (i.e. 2.10.5, latest release, see https://github.com/coin-or/Cbc/releases). These files were produced based on a modified version of the PKGBUILD file present in the [r-windows/rtools-packages](https://github.com/r-windows/rtools-packages) repository on Windows 10 (i.e. https://github.com/r-windows/rtools-packages/tree/master/mingw-w64-coinor-cbc, copied below). To verify that this PR works as expected, I have created a fork of the [rcbc package](https://github.com/dirkschumacher/rcbc) (currently the only package that uses CBC to my knowledge) and modified it to use these new files (via a new release, https://github.com/jeffreyhanson/cbc/releases/tag/v2.10.5). This fork was then tested using GitHub Actions workflows (see https://github.com/jeffreyhanson/rcbc/pull/3, and specifically https://github.com/jeffreyhanson/rcbc/actions/runs/699552449) and also locally (under both i386 and x64 on Windows 7). If/after this PR is accepted, I plan to submit a PR to the [rcbc package GitHub repository](https://github.com/dirkschumacher/rcbc) so that it fetches the new version of CBC from this rwinlib repository.

@jeroen, what do you think? Please let me know if you require any additional changes or testing to accept this PR? I was not entirely sure  what the correct naming scheme for the folders are? Although this repository previously had the folder "lib-4.9.3", I noticed that other repositories in this orgniazation have started using the "lib" folder (e.g. https://github.com/rwinlib/freetype). I am happy to change the folder naming conventions as needed?

--------------------

```
# Maintainer: Jeroen Ooms <jeroenooms@gmail.com>

_realname=Cbc
pkgbase=mingw-w64-coinor-cbc
pkgname=("${MINGW_PACKAGE_PREFIX}-coinor-cbc")
pkgver=2.10.5
pkgrel=9100
pkgdesc="Coin-or branch and cut (mingw-w64)"
arch=('any')
url='http://www.coin-or.org'
source=("https://www.coin-or.org/download/source/${_realname}/${_realname}-${pkgver}.tgz")
sha256sums=('da1a945648679b21ba56b454b81e939451dc7951d9beb3c3e14f18f64dde6972')
groups=("rtools-coinor-cbc")

build() {
  cd "$srcdir"/${_realname}-${pkgver}
  [[ -d "${srcdir}"/build-${CARCH} ]] && rm -rf "${srcdir}"/build-${CARCH}
  mkdir -p "${srcdir}"/build-${CARCH} && cd "${srcdir}"/build-${CARCH}

  export enable_bzlib=no
  ../Cbc-${pkgver}/configure \
    --prefix=${MINGW_PREFIX} \
    --build=${MINGW_CHOST} \
    --host=${MINGW_CHOST} \
    --target=${MINGW_CHOST}

  make
}

package() {
  cd "${srcdir}"/build-${CARCH}
  make install DESTDIR="${pkgdir}"
}
```

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks. How did you modify the PKGBUILD? Maybe we should update the official PKGBUILD if needed? Can you send a PR for that?

**Comment by jeffreyhanson** [comment]
Yeah that's a great idea! I'll submit a PR to the r-windows repo now.

@ricschuster sent me the modified PKGBUILD file -- so please correct me if I'm wrong -- but my understanding is that the only changes were in the `pkgver` and `sha256sums` fields of the PKGBUILD file. For reference, here are relevant lines from the [current PKGBUILD file](https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-coinor-cbc/PKGBUILD):

```
pkgver=2.9.9
sha256sums=('aa8404e49b25853b30ebd6291e3beedc9b5f583e3c0c36822fae17507feb0af1')
```

and here are the relevant lines from the modified PKGBUILD file (copied from above):

```
pkgver=2.10.5
sha256sums=('da1a945648679b21ba56b454b81e939451dc7951d9beb3c3e14f18f64dde6972')
```

**Comment by jeffreyhanson** [comment]
Ok I've just created the PR with the modified PKGBUILD file (linked above). Let me know if there's anything I can do to help with the PRs?

**Comment by jeroen** [comment]
Thanks! I merged the artifacts from the rtools-packages build in https://github.com/rwinlib/cbc/releases/tag/v2.10.5

**Comment by jeffreyhanson** [comment]
Legend - thank you very much @jeroen!

**Pull request closed without merging**
